version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: redwoodblogdb
    ports:
      - 5560:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
